{{- if .Values.createPostgresqlSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  {{- if .Release.IsUpgrade }}
    {{- if (index (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret -}}
      # check to see if secret already exists in namespace.
       postgresql-postgres-password: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.existingSecret ).data "postgresql-password" }}
    {{ else }}
    # if a secret isn't found when perfroming an upgrade create a new secret.
      {{- if .Values.postgresql.postgresqlPassword }}
        postgresql-postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
      {{- else }}
        {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
        postgresql-postgres-password: {{ $postgresRandomPassword }}
      {{- end }}
    {{- end }}
  {{ else }}
# Perform normal install operation
    {{- if .Values.postgresql.postgresqlPassword }}
      postgresql-postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
    {{- else }}
      {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
      postgresql-postgres-password: {{ $postgresRandomPassword }}
    {{- end }}
  {{- end }}
{{- end }}
